name: TriggerReactor
main: io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor
version: 3.3.0.9-Beta
author: wysohn
authors:
- soliddanii
- MidnightSugar
- TheBestNightSky
- dltks0306
- RubrumExPlaneta
- Alex4386
- RedLime
- mrandriyg
- Dr_Romantic
- gerzytet
- Kuiprux
- Ioloolo
- Sayakie
- soshimee
softdepend:
- Vault
- PlaceholderAPI
- mcMMO
- CoreProtect
- ProtocolLib
- WorldGuard
- NashornJs
commands:
  triggerreactor:
    aliases:
    - trg
    description: Simple script parser with infinite possibility
permissions:
  triggerreactor.admin:
    description: Grant admin permission
command:
  triggerreactor:
    aliases:
    - trg
    description: Simple script parser with infinite possibility
api-version: 1.13
