name: TriggerReactor
main: io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor
version: 2.1.7
author: wysohn
authors:
- soliddanii
- MidnightSugar
- TheBestNightSky
- dltks0306
- RubrumExPlaneta
- Alex4386
- RedLime
- mrandriyg
- professer_snape
softdepend:
- Vault
- PlaceholderAPI
- mcMMO
- TheGuild
- CoreProtect
- ProtocolLib
- WorldGuard
commands:
  triggerreactor:
    aliases:
    - trg
    description: trigger reactor
permissions:
  triggerreactor.admin:
    description: Grants access to commands
