name: 'PR Triage'
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review, labeled, unlabeled]

jobs:
  pr-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    name: PR Triage
    steps:
      - name: Automatically label PR
        uses: actions/labeler@v4.0.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
