name: 'PR Triage'
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review, labeled, unlabeled]

jobs:
  pr-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    name: PR Triage
    steps:
      - name: Automatically label PR
        uses: actions/labeler@v4.0.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true

      - name: Automatically assign reviewers
        if: github.event.action == 'opened' || github.event.action == 'ready_for_review'
        uses: octokit/request-action@v2.1.9
        with:
          route: POST /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
          team_reviewers: '["maintainers"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
